#!/bin/sh
#
# Starts smartmeter-exporter.
#

DAEMON="smartmeter-exporter"
PIDFILE="/var/run/$DAEMON.pid"

# Allow a few customizations from a config file
[ -r "/etc/default/$DAEMON" ] && . "/etc/default/$DAEMON"

SMARTMETER_EXPORTER_LOGFILE="/var/log/$DAEMON.log"

start() {
	printf 'Starting %s: ' "$DAEMON"
	umask 077

	start-stop-daemon -S -q -b -m -p "$PIDFILE" -x /bin/sh \
		-- -c "$DAEMON $SMARTMETER_EXPORTER_ARGS > $SMARTMETER_EXPORTER_LOGFILE 2>&1"
	status=$?
	[ $status = 0 ] && echo "OK" || echo "FAIL"
	return "$status"
}
stop() {
	printf 'Stopping %s: ' "$DAEMON"
	start-stop-daemon -K -q -p "$PIDFILE"
	status=$?
	[ $status = 0 ] && echo "OK" || echo "FAIL"
	return "$status"
}
restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $status
